### ISSUE TITLE
Remove dist folder from repo

### ISSUE THREAD

**Issue by humphd** [JiaHua-Zou/Jia_SSG#10]
You want to include all source code in the repo, but generated assets like `dist` should be ignored and left out.  You can use `git rm -fr dist` to remove it, and add a `.gitignore` file that includes `dist` to have git ignore it later.  `npx gitignore node` will generate one for you.

**Comment by JiaHua-Zou** [comment]
I have remove the dist folder. [Branch was done on](https://github.com/JiaHua-Zou/Jia_SSG/tree/6c9c9a4b9cf152104ad41e0906a8ee3a7ea94cde)
