### ISSUE TITLE
Title detection detects the whole file as title

### ISSUE THREAD

**Issue by lmpham1** [JiaHua-Zou/Jia_SSG#2]
### Description
The program uses the whole file content as the title

### Reproduction
__input file:__
![image](https://user-images.githubusercontent.com/43410858/133535570-3488fa57-affe-4d46-836d-000c30c627c3.png)

__start the program__:
`node index.js "test with paragraph.txt"`

__output:__
![image](https://user-images.githubusercontent.com/43410858/133535654-e19b01ac-4538-42be-a920-46ca3139a74e.png)

__expected output:__
![image](https://user-images.githubusercontent.com/43410858/133535697-47325a42-4124-4776-a01c-936c0a69c48e.png)

### Proposed Solution
It seems that files on Windows have '\r\n' as newline characters instead of just '\n'. Current title detection seems to be only detecting '\n'. Detection of '\r\n' should be added.

**Comment by JiaHua-Zou** [comment]
My split code was not splitting correctly.

### Bug located
```js
 const title = dat.split("\n\n\n");
  const text = dat.slice(dat.search("\n\n\n") + 3);
```

### Code Change to:

```js
  var fileName = "";
  var text = ""; 
  var title = src.match(/^.+(\r?\n\r?\n\r?\n)/) || "";

  if (!title) {
    fileName = fileDirName.slice(0, -5);
    text = src;
  } else {
    fileName = title[0].trim();
    title = title[0].trim()
    text = src.substring(fileName.length + 3);
  }
```

I have change the bug to the new code, It will now generate the title in ```<h1>```.
