### ISSUE TITLE
Fix license field in package.json to match MIT License chosen

### ISSUE THREAD

**Issue by humphd** [JiaHua-Zou/Jia_SSG#7]
The project is using the MIT License, but lists the 'ICS' license at https://github.com/JiaHua-Zou/Jia_SSG/blob/main/package.json#L16.  This should be changed to `MIT`

**Comment by JiaHua-Zou** [comment]
![image](https://user-images.githubusercontent.com/59105665/134214792-50825500-0ec3-44e4-84f2-f7fbd6b16d89.png)

License has been change from `ISC` to `MIT` in the `package.json` file
