### ISSUE TITLE
Have version info come from package.json

### ISSUE THREAD

**Issue by humphd** [JiaHua-Zou/Jia_SSG#8]
https://github.com/JiaHua-Zou/Jia_SSG/blob/main/index.js#L7 is hard-coding the version to an incorrect value.  I would pull it directly from the `package.json` file, so it's always recent:

```js
const { version } = require('./package.json');
// version is now the correct version string
```

**Comment by JiaHua-Zou** [comment]
![image](https://user-images.githubusercontent.com/59105665/134215100-1bb81776-c575-4edf-a9c0-6e44a0838b48.png)

Have updated the `package.json` to call the correct version when `-v or --version` is used.
